version: '3'
services:
  machine1:
    image: ubuntu:18.04
    #command: tail -f /dev/null
    environment:
      - METHOD=md5
      - POSTGRES_PASSWORD=pg_password
  machine2:
    build:
      context: .
      dockerfile: python.Dockerfile
      args:
        - python_version
