name: thingie

on: [push, pull_request]

jobs:
  example-job:
    name: w-python-${{ matrix.python }}
    strategy:
      matrix:
        python: ['2.7','3.4']
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./scripts
    steps:
      - name: Check out the repository to the runner
        uses: actions/checkout@v4  
      - name: Run a script
        run: ./my-script.sh "${{ matrix.python }}"
      - name: Run another script
        run: ./my-other-script.sh
